"""hub.model_card.generate_card -- shape + critical brief-rule asserts.

Sections come from brief 6.1 item 4. Critical: brief 16.2 forbids any AI
attribution in shipped artifacts; the card is shipped, so audit it here.
"""

from pathlib import Path

import pytest

from tooltuned_qwen.hub.model_card import generate_card

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_YAML = REPO_ROOT / "configs" / "default.yaml"


def test_card_renders_with_bfcl_tbd(tmp_path: Path) -> None:
    """Phase 3.3 path -- card regenerates without BFCL numbers."""
    out = tmp_path / "MODEL_CARD.md"
    written = generate_card(
        bfcl_results=None,
        training_config_path=str(DEFAULT_YAML),
        out_path=str(out),
    )
    body = Path(written).read_text(encoding="utf-8")

    # Brief 6.1 item 4 sections.
    for section in (
        "## TL;DR",
        "## BFCL V4 results",
        "## Training data",
        "## Training procedure",
        "## Hyperparameters",
        "## Intended use",
        "## Out of scope",
        "## Limitations",
        "## License",
        "## Reproduction",
        "## Citation",
        "## Author",
    ):
        assert section in body, f"missing {section}"

    assert "TBD (Phase 4)" in body
    assert "license: apache-2.0" in body  # frontmatter
    assert "base_model: Qwen/Qwen3.5-4B" in body
    assert "Sukhrob Nurali" in body
    # default.yaml pins the public W&B team workspace; the card must
    # surface the dashboard link so reviewers can audit training curves.
    assert "https://wandb.ai/sukhrob-production/tooltuned-qwen" in body


def test_card_renders_with_bfcl_results(tmp_path: Path) -> None:
    """Phase 4 path -- once results land, the table fills in. Schema is the
    one documented at the top of model_card.py; lock it now so Phase 4 has a
    contract to fill against."""
    out = tmp_path / "MODEL_CARD.md"
    generate_card(
        bfcl_results={
            "overall_base": 0.503,
            "overall_tuned": 0.547,
            "delta": 0.044,
            "n_total": 1234,
            "evaluated_at": "2026-05-15",
            "base_model": "Qwen/Qwen3.5-4B",
            "rows": [
                {"category": "simple", "base": 0.62, "tuned": 0.71},
                {"category": "multiple", "base": 0.41, "tuned": 0.48},
            ],
        },
        training_config_path=str(DEFAULT_YAML),
        out_path=str(out),
    )
    body = out.read_text(encoding="utf-8")

    assert "TBD (Phase 4)" not in body
    assert "54.7%" in body  # tuned headline (0.547)
    assert "+4.4pp" in body  # delta with sign
    assert "Per-category breakdown" in body
    assert "n=1234" in body


def test_card_has_no_ai_attribution(tmp_path: Path) -> None:
    """Brief 16.2: zero AI mentions in shipped artifacts. Audit the body."""
    out = tmp_path / "MODEL_CARD.md"
    generate_card(
        bfcl_results=None,
        training_config_path=str(DEFAULT_YAML),
        out_path=str(out),
    )
    body = out.read_text(encoding="utf-8").lower()

    for forbidden in ("claude", "anthropic", "co-authored", "generated by", "chatgpt"):
        assert forbidden not in body, f"forbidden token in card: {forbidden}"


def test_card_emits_dashboard_link_when_entity_set(tmp_path: Path) -> None:
    """Caller can pass `wandb_dashboard` explicitly; this is the path the
    user takes once they've chosen a public W&B entity. Verifies the link
    actually lands in the rendered body."""
    out = tmp_path / "MODEL_CARD.md"
    generate_card(
        bfcl_results=None,
        training_config_path=str(DEFAULT_YAML),
        out_path=str(out),
        wandb_dashboard="https://wandb.ai/sukhrob-production/tooltuned-qwen",
    )
    body = out.read_text(encoding="utf-8")
    assert "https://wandb.ai/sukhrob-production/tooltuned-qwen" in body


def test_card_returns_absolute_path(tmp_path: Path) -> None:
    out = tmp_path / "MODEL_CARD.md"
    written = generate_card(
        bfcl_results=None,
        training_config_path=str(DEFAULT_YAML),
        out_path=str(out),
    )
    assert Path(written).is_absolute()
    assert Path(written).exists()


def test_card_negative_delta_renders_with_minus(tmp_path: Path) -> None:
    """If we ever ship a regression by mistake, the headline must show it
    rather than silently flipping the sign."""
    out = tmp_path / "MODEL_CARD.md"
    generate_card(
        bfcl_results={
            "overall_base": 0.503,
            "overall_tuned": 0.480,
            "delta": -0.023,
            "n_total": 500,
            "evaluated_at": "2026-05-15",
        },
        training_config_path=str(DEFAULT_YAML),
        out_path=str(out),
    )
    body = out.read_text(encoding="utf-8")
    assert "-2.3pp" in body
    assert "+2.3pp" not in body


@pytest.mark.parametrize("missing_key", ["overall_base", "overall_tuned", "delta"])
def test_card_falls_back_to_tbd_on_partial_results(
    tmp_path: Path, missing_key: str
) -> None:
    """A half-filled dict shouldn't render as if Phase 4 succeeded -- the
    headline degrades to TBD instead of e.g. crashing on None * 100."""
    full = {
        "overall_base": 0.5,
        "overall_tuned": 0.55,
        "delta": 0.05,
        "n_total": 100,
    }
    full.pop(missing_key)
    out = tmp_path / "MODEL_CARD.md"
    generate_card(
        bfcl_results=full,
        training_config_path=str(DEFAULT_YAML),
        out_path=str(out),
    )
    body = out.read_text(encoding="utf-8")
    assert "TBD (Phase 4)" in body
